env:
  node: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
globals:
  - console
plugins:
  - react
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
no-console:
  - "error"
  - allow:
    - "info"
    - "warn"
    - "error"
