server:
  port: 8889
index: 'index.html'
login: 'login.html'
maxAgeResources: 0
database:
  web: mongodb://localhost:27017/tychyKonkurs
  admin: mongodb://localhost:27017/configuration
bigscreenChannel: 'http://localhost:8085'
