server:
  port: 8889
index: 'index'
maxAgeResources: 0
database:
  web: mongodb://localhost:27017/tychyKonkurs
  admin: mongodb://localhost:27017/configuration
bigscreenChannel: 'http://localhost:8085'
frontendConfig:
  projectorUrl: 'http://localhost:8888'
