bigscreenChannel: 'http://40.115.23.130/'
index: 'index-production'
frontendConfig:
  projectorUrl: 'http://40.115.23.130/projector'
database:
  web: mongodb://localhost:27017/development
  admin: mongodb://localhost:27017/configuration